# Способы изображения и графические средства {#map-symbology}

## Исходные данные {#map-symbology-initial-data}

[Варианты заданий](https://drive.google.com/drive/folders/1hbb13IYlOQN_QSebxW7OpPvh8j90zwDm){target="_blank"}

[Бланк задания](https://yadi.sk/i/8Jka8SVegwxeqw){target="_blank"}

## Графические переменные {#map-symbology-variables}
[В начало справки ⇡](#map-symbology)

Классические графические переменные были предложены Ж. Бертеном. С помощью них осуществляется семантическая дифференциация содержания карты.

Графические переменные    |Терминология ГИС ПО
--------------------------|-----------------------
`Цвет`                    |`Hue`
`Оттенок`                 |`Saturation, value`
`Форма`                   |`Marker symbol`
`Размер`                  |`Size`
`Ориентировка`            |`Rotation`
`Структура`               |`Marker fill, line fill`

При работе с геоинформационным программным обеспечением вам следует иметь в виду, что на данный момент в картографии доступно уже больше графических переменных – например, прозрачность, анимация и другие.

**Графические средства** – это конкретная реализация графических переменных на карте.

## Способы изображения {#map-symbology-methods}
[В начало справки ⇡](#map-symbology)

Подробнее о способах изображения вы можете узнать из учебника А.М. Берлянта [[Берлянт, 2002](https://yadi.sk/i/Fg77Q031F0lMoQ){target="_blank"}], еще подробнее – из учебника К.А. Салищева [[Салищев, 1982](https://yadi.sk/i/e9gW1TmzdEUQqg){target="_blank"}].

Способы изображения       | Локализация          |Тип геометрии в БПД
--------------------------|----------------------|-------------------------
`Значки`                  |`точечная`            |`точка`, `мультиточка`
`Линейные знаки`          |`линейная`            |`линия`, `мультилиния`
`Знаки движения`          |`линейная`            |`линия`, `мультилиния`
`Качественный фон`        |`площадная сплошная`  |`полигон`, `мультиполигон`
`Количественный фон`      |`площадная сплошная`  |`полигон`, `мультиполигон`
`Изолинии`                |`площадная сплошная`  |`растр`, `линия`, `полигон`
`Картограммы`             |`площадная сплошная`  |`полигон`, `мультиполигон`
`Картодиаграммы`          |`площадная сплошная`  |`полигон`, `мультиполигон`
`Точечный способ`         |`площадная рассеянная`|`полигон`, `мультиполигон`
`Ареалы`                  |`площадная рассеянная`|`полигон`, `мультиполигон`
`Локализованные диаграммы`|`условно точечная`    |`точка`

При работе с геоинформационным программным обеспечение вам следует иметь в виду, что далеко не все способы изображения доступны для автоматизированного построения. В некоторых случаях требуется конвертация карты в графический формат и её редактирование в графических пакетах.

----
_Карпачевский А.М._ **Картография: практикум в QGIS**. М.: Географический факультет МГУ, `r lubridate::year(Sys.Date())`.
----